# Generated by Django 5.0 on 2023-12-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_dashboard', '0002_remove_product_product_type_remove_product_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='Available', max_length=14),
        ),
    ]
