# Generated by Django 5.0 on 2023-12-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_p', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=400)),
                ('image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
