# Generated by Django 5.0 on 2023-12-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='slugC',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='slugP',
            field=models.SlugField(default=None),
        ),
    ]
