# Generated by Django 5.0 on 2023-12-28 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_collection_slugc_product_slugp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slugP',
        ),
    ]
