# Generated by Django 5.0 on 2024-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_delete_product'),
        ('vendor_dashboard', '0004_alter_product_type_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('phone_nbr', models.CharField(max_length=30)),
                ('postal_code', models.CharField(default='00000', max_length=10)),
                ('products', models.ManyToManyField(to='vendor_dashboard.product')),
            ],
        ),
    ]
