# Generated by Django 5.0 on 2024-01-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='No comment ', max_length=25),
        ),
    ]
